### ISSUE TITLE
Javítások

### ISSUE THREAD

**Issue by Zsena** [GretaFa/Bootstrap-4#1]
- A html neve ne legyen vesszővel elválasztva vagy kötőjellel, legyen sima index.html
- a sticky footer hiányzik, csináld majd meg légyszives
- a menüre nem lehet kattintani, valami nincs jól lezárva az 'a' tagekben, mert cursor pointert mutat, nem tudok beleirni az inputba, rányomni a dropdown menüre, ugyanez a jumbotronnál. Töröld ki egyesével a szekciókat és nézd meg mi okozza a problémát. 
(Help: relative class kell a csomagoló (wrapper) elemnek, ha teljes kártya kattinthatóságot csinálsz a stretched-link osztállyal.
- mobilon a kártyák közé rakj eltartást
- mobilon a jumbotronnak ne legyen x tengelyen paddingje
- cdn-ről van behúzva a BS, akkor így felesleges a css mappa jelenleg, töröld légyszives

**Comment by GretaFa** [comment]
Kész vannak, pusholom
